language: c
compiler:
  - clang
  - gcc
before_install:
  - "sudo apt-get -qq update"
  - "if [ ! $CC = 'clang' ]; then sudo apt-get -qq install gcc-msp430 msp430-libc msp430mcu; fi"
  - "if [ ! $CC = 'clang' ]; then sudo apt-get -qq install gcc-avr avr-libc; fi"
script:
  - "make -C src libxively"
  - "make -C src tests XI_UNIT_TEST_TARGET=native"
  - "if [ ! $CC = 'clang' ]; then make ci_msp430; fi"
  - "if [ ! $CC = 'clang' ]; then make ci_avr; fi"
